[package]
name = "simple-pub-sub"
version = "0.1.0"
authors = ["Martin Levesque <levesque.martin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = "0.4.19"
threadpool = "1.8.1"

